# ---------------------------------------------------------------------------
# pg_hba.conf for the PRIMARY.
# Allows local + intra-compose-network connections and replication.
# ---------------------------------------------------------------------------
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# App + pgbouncer + replica live on the docker bridge network.
host    all             all             0.0.0.0/0               scram-sha-256

# Replication connections from the replica.
host    replication     replicator      0.0.0.0/0               scram-sha-256
